# Generated by Django 3.2.25 on 2025-06-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='health_professional_body',
            field=models.CharField(choices=[('HPCSA', 'Health Professions Council of South Africa'), ('SANC', 'South African Nursing Council'), ('SAPC', 'South African Pharmacy Council'), ('SADTC', 'South African Dental Technicians Council'), ('AHPCSA', 'Allied Health Professions Council of South African')], default='HPCSA', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(choices=[('medical_doctor', 'Medical Doctor'), ('dentist', 'Dentist'), ('psychologist', 'Psychologist'), ('physiotherapist', 'Physiotherapist'), ('radiographer', 'Radiographer'), ('occupational_therapist', 'Occupational Therapist'), ('biokineticist', 'Biokineticist'), ('clinical_technologist', 'Clinical Technologist'), ('dietitian', 'Dietitian'), ('audiologist', 'Audiologist'), ('optometrist', 'Optometrist'), ('emergency_care_practitioner', 'Emergency Care Practitioner'), ('registered_nurse', 'Registered Nurse'), ('enrolled_nurse', 'Enrolled Nurse'), ('nursing_assistant', 'Nursing Assistant'), ('midwife', 'Midwife'), ('pharmacist', 'Pharmacist'), ('pharmacy_assistant', 'Pharmacy Assistant'), ('pharmacist_intern', 'Pharmacist Intern'), ('dental_technician', 'Dental Technician'), ('dental_technologist', 'Dental Technologist'), ('chiropractor', 'Chiropractor'), ('homeopath', 'Homeopath'), ('naturopath', 'Naturopath'), ('osteopath', 'Osteopath'), ('acupuncturist', 'Acupuncturist'), ('traditional_health_practitioner', 'Traditional Health Practitioner')], default='dentist', max_length=64),
        ),
    ]
