# Generated by Django 3.2.25 on 2025-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20250609_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(choices=[('medical_doctor', 'Medical Doctor'), ('dentist', 'Dentist'), ('psychologist', 'Psychologist'), ('physiotherapist', 'Physiotherapist'), ('radiographer', 'Radiographer'), ('occupational_therapist', 'Occupational Therapist'), ('biokineticist', 'Biokineticist'), ('clinical_technologist', 'Clinical Technologist'), ('dietitian', 'Dietitian'), ('audiologist', 'Audiologist'), ('optometrist', 'Optometrist'), ('emergency_care_practitioner', 'Emergency Care Practitioner'), ('registered_nurse', 'Registered Nurse'), ('enrolled_nurse', 'Enrolled Nurse'), ('nursing_assistant', 'Nursing Assistant'), ('midwife', 'Midwife')], default='dentist', max_length=64),
        ),
    ]
