# Generated by Django 3.2.25 on 2025-06-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_profile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reg_num',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='health_professional_body',
            field=models.CharField(choices=[('HPCSA', 'Health Professions Council of South Africa'), ('SANC', 'South African Nursing Council')], default='HPCSA', max_length=64),
        ),
    ]
