# Generated by Django 3.2.25 on 2025-06-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20250612_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_number',
        ),
    ]
