# Generated by Django 3.2.25 on 2025-07-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default/default_profile_pic.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
