# Generated by Django 5.2.4 on 2025-07-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default/default_profile_pic.jpg', null=True, upload_to='profile/'),
        ),
    ]
