# Generated by Django 3.2.25 on 2025-07-14 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0008_patient_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CariesRiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('features_used', models.JSONField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
