# Generated by Django 3.2.25 on 2025-06-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DentalScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_treatment', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('income', models.CharField(max_length=20)),
                ('sugar_meals', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('sugar_snacks', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('sugar_beverages', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('sa_citizen', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('special_needs', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('plaque', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('dry_mouth', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('enamel_defects', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('appliance', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('fluoride_water', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('fluoride_toothpaste', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('topical_fluoride', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('regular_checkups', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('sealed_pits', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('restorative_procedures', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('enamel_change', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('dentin_discoloration', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('white_spot_lesions', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('cavitated_lesions', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('multiple_restorations', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('missing_teeth', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('teeth_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
