# Generated by Django 3.2.25 on 2025-06-17 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20250612_1602'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalscreening',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='patient.patient'),
            preserve_default=False,
        ),
    ]
