# Generated by Django 3.2.25 on 2025-06-29 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20250612_1602'),
        ('assessments', '0002_dentalscreening_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet_sugary_foods', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('sweet_sugary_foods_daily', models.CharField(blank=True, max_length=20, null=True)),
                ('sweet_sugary_foods_weekly', models.CharField(blank=True, max_length=20, null=True)),
                ('cold_drinks_juices', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('cold_drinks_juices_daily', models.CharField(blank=True, max_length=20, null=True)),
                ('cold_drinks_juices_weekly', models.CharField(blank=True, max_length=20, null=True)),
                ('takeaways_processed_foods', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('takeaways_processed_foods_daily', models.CharField(blank=True, max_length=20, null=True)),
                ('takeaways_processed_foods_weekly', models.CharField(blank=True, max_length=20, null=True)),
                ('salty_snacks', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('salty_snacks_daily', models.CharField(blank=True, max_length=20, null=True)),
                ('salty_snacks_weekly', models.CharField(blank=True, max_length=20, null=True)),
                ('spreads', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('spreads_daily', models.CharField(blank=True, max_length=20, null=True)),
                ('spreads_weekly', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_screenings', to='patient.patient')),
            ],
        ),
    ]
