# Generated by Django 3.2.25 on 2025-06-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_dietaryscreening'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryscreening',
            name='added_sugars',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='added_sugars_bedtime',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='added_sugars_daily',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='added_sugars_timing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='added_sugars_weekly',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='cold_drinks_juices_bedtime',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='cold_drinks_juices_timing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='dairy_products',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='dairy_products_daily',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='dairy_products_weekly',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='fresh_fruit',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='fresh_fruit_bedtime',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='fresh_fruit_daily',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='fresh_fruit_timing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='fresh_fruit_weekly',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='processed_fruit',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='processed_fruit_bedtime',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='processed_fruit_daily',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='processed_fruit_timing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='processed_fruit_weekly',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='salty_snacks_timing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='spreads_bedtime',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='spreads_timing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='sweet_sugary_foods_bedtime',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='sweet_sugary_foods_timing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='vegetables',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='vegetables_daily',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='vegetables_weekly',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='water',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='water_glasses',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='water_timing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='xylitol_products',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='xylitol_products_daily',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dietaryscreening',
            name='xylitol_products_weekly',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
