# Generated by Django 3.2.25 on 2025-07-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_update_dietary_screening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalscreening',
            name='income',
        ),
        migrations.RemoveField(
            model_name='dentalscreening',
            name='sugar_beverages',
        ),
        migrations.RemoveField(
            model_name='dentalscreening',
            name='sugar_meals',
        ),
        migrations.RemoveField(
            model_name='dentalscreening',
            name='sugar_snacks',
        ),
        migrations.RemoveField(
            model_name='dietaryscreening',
            name='xylitol_products',
        ),
        migrations.RemoveField(
            model_name='dietaryscreening',
            name='xylitol_products_daily',
        ),
        migrations.RemoveField(
            model_name='dietaryscreening',
            name='xylitol_products_weekly',
        ),
    ]
