# Generated by Django 5.2.4 on 2025-08-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_auto_20250714_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryscreening',
            name='added_sugars_daily',
            field=models.CharField(blank=True, choices=[('1-3_day', '1-3 times per day'), ('3-4_day', '3-4 times per day'), ('4-6_day', '4-6 times per day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='added_sugars_timing',
            field=models.CharField(blank=True, choices=[('with_meals', 'With meals'), ('between_meals', 'Between meals'), ('both', 'Both')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='added_sugars_weekly',
            field=models.CharField(blank=True, choices=[('1-3_week', '1-3 times per week'), ('3-4_week', '3-4 times per week'), ('4-6_week', '4-6 times per week')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='cold_drinks_juices_daily',
            field=models.CharField(blank=True, choices=[('1-3_day', '1-3 times per day'), ('3-4_day', '3-4 times per day'), ('4-6_day', '4-6 times per day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='cold_drinks_juices_timing',
            field=models.CharField(blank=True, choices=[('with_meals', 'With meals'), ('between_meals', 'Between meals'), ('both', 'Both')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='cold_drinks_juices_weekly',
            field=models.CharField(blank=True, choices=[('1-3_week', '1-3 times per week'), ('3-4_week', '3-4 times per week'), ('4-6_week', '4-6 times per week')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='dairy_products_daily',
            field=models.CharField(blank=True, choices=[('1-3_day', '1-3 times per day'), ('3-4_day', '3-4 times per day'), ('4-6_day', '4-6 times per day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='dairy_products_weekly',
            field=models.CharField(blank=True, choices=[('1-3_week', '1-3 times per week'), ('3-4_week', '3-4 times per week'), ('4-6_week', '4-6 times per week')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='fresh_fruit_daily',
            field=models.CharField(blank=True, choices=[('1-3_day', '1-3 times per day'), ('3-4_day', '3-4 times per day'), ('4-6_day', '4-6 times per day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='fresh_fruit_timing',
            field=models.CharField(blank=True, choices=[('with_meals', 'With meals'), ('between_meals', 'Between meals'), ('both', 'Both')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='fresh_fruit_weekly',
            field=models.CharField(blank=True, choices=[('1-3_week', '1-3 times per week'), ('3-4_week', '3-4 times per week'), ('4-6_week', '4-6 times per week')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='processed_fruit_daily',
            field=models.CharField(blank=True, choices=[('1-3_day', '1-3 times per day'), ('3-4_day', '3-4 times per day'), ('4-6_day', '4-6 times per day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='processed_fruit_timing',
            field=models.CharField(blank=True, choices=[('with_meals', 'With meals'), ('between_meals', 'Between meals'), ('both', 'Both')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='processed_fruit_weekly',
            field=models.CharField(blank=True, choices=[('1-3_week', '1-3 times per week'), ('3-4_week', '3-4 times per week'), ('4-6_week', '4-6 times per week')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='salty_snacks_daily',
            field=models.CharField(blank=True, choices=[('1-3_day', '1-3 times per day'), ('3-4_day', '3-4 times per day'), ('4-6_day', '4-6 times per day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='salty_snacks_timing',
            field=models.CharField(blank=True, choices=[('with_meals', 'With meals'), ('between_meals', 'Between meals'), ('both', 'Both')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='salty_snacks_weekly',
            field=models.CharField(blank=True, choices=[('1-3_week', '1-3 times per week'), ('3-4_week', '3-4 times per week'), ('4-6_week', '4-6 times per week')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='spreads_daily',
            field=models.CharField(blank=True, choices=[('1-3_day', '1-3 times per day'), ('3-4_day', '3-4 times per day'), ('4-6_day', '4-6 times per day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='spreads_timing',
            field=models.CharField(blank=True, choices=[('with_meals', 'With meals'), ('between_meals', 'Between meals'), ('both', 'Both')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='spreads_weekly',
            field=models.CharField(blank=True, choices=[('1-3_week', '1-3 times per week'), ('3-4_week', '3-4 times per week'), ('4-6_week', '4-6 times per week')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='sweet_sugary_foods_daily',
            field=models.CharField(blank=True, choices=[('1-3_day', '1-3 times per day'), ('3-4_day', '3-4 times per day'), ('4-6_day', '4-6 times per day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='sweet_sugary_foods_timing',
            field=models.CharField(blank=True, choices=[('with_meals', 'With meals'), ('between_meals', 'Between meals'), ('both', 'Both')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='sweet_sugary_foods_weekly',
            field=models.CharField(blank=True, choices=[('1-3_week', '1-3 times per week'), ('3-4_week', '3-4 times per week'), ('4-6_week', '4-6 times per week')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='takeaways_processed_foods_daily',
            field=models.CharField(blank=True, choices=[('1-3_day', '1-3 times per day'), ('3-4_day', '3-4 times per day'), ('4-6_day', '4-6 times per day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='takeaways_processed_foods_weekly',
            field=models.CharField(blank=True, choices=[('1-3_week', '1-3 times per week'), ('3-4_week', '3-4 times per week'), ('4-6_week', '4-6 times per week')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='vegetables_daily',
            field=models.CharField(blank=True, choices=[('1-3_day', '1-3 times per day'), ('3-4_day', '3-4 times per day'), ('4-6_day', '4-6 times per day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='vegetables_weekly',
            field=models.CharField(blank=True, choices=[('1-3_week', '1-3 times per week'), ('3-4_week', '3-4 times per week'), ('4-6_week', '4-6 times per week')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='water_glasses',
            field=models.CharField(blank=True, choices=[('<2', 'Less than 2 glasses'), ('2-4', '2-4 glasses'), ('5+', '5 or more glasses')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryscreening',
            name='water_timing',
            field=models.CharField(blank=True, choices=[('with_meals', 'With meals'), ('between_meals', 'Between meals'), ('after_sweets', 'After eating sweets'), ('before_bedtime', 'Before bedtime')], max_length=50, null=True),
        ),
    ]
