# Generated by Django 3.2.25 on 2025-06-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='parent_contact',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
