# Generated by Django 3.2.25 on 2025-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_parent_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female')], default='0', max_length=1),
        ),
    ]
