# Generated by Django 3.2.25 on 2025-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='parent_contact',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parent_id',
            field=models.CharField(max_length=13),
        ),
    ]
