# Generated by Django 3.2.25 on 2025-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20250608_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='parent_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='parent_surname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
