# Generated by Django 3.2.25 on 2025-06-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20250612_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parent_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parent_surname',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname',
            field=models.CharField(max_length=64),
        ),
    ]
