# Generated by Django 3.2.25 on 2025-07-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patient_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
