# Generated by Django 3.2.25 on 2025-06-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, max_length=199, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('hours', models.CharField(blank=True, max_length=64, null=True)),
                ('emergency', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
