# Generated by Django 3.2.25 on 2025-06-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
